### ISSUE TITLE
Documentation has console errors/warnings

### ISSUE THREAD

**Issue by chrisdwheatley** [nearform/saluki#55]
**Describe the bug**

When navigating to https://nearform.github.io/saluki there are errors/warnings in the console. We're using https://github.com/c8r/x0 for docs.

**Comment by adaschevici** [comment]
i tried running the npm scripts for generating the documentation but the `0x` just seems to hang after it does the build.

**Comment by adaschevici** [comment]
the warnings seem to be coming from the routes + styled component implicit conversion that is passed into the styled-components, needs some further investigation
```
  return (
    <SidebarLayout title={'Saluki'} {...props} routes={r}>
```

**Comment by chrisdwheatley** [comment]
No longer applicable, docs have been removed for time being.
