### ISSUE TITLE
Allow ability to pass custom string into Saluki function

### ISSUE THREAD

**Issue by chrisdwheatley** [nearform/saluki#73]
**Is your feature request related to a problem? Please describe.**

Currently, if you want to pass a custom rule into a function saluki exposes, such as breakpoint or psuedo, you have to pass it in as an object. For example;

```js
${breakpoint.large({ width: "700px" })}
```

This feels jarring when you're in a tagged template literal as you've swapping between writing CSS and object notations.

**Describe the solution you'd like**

Ideally you'd be able to write;

```js
${breakpoint.large('width: 700px;')}
```

As well as still supporting objects and possibly arrays thanks to #71.

**Comment by adaschevici** [comment]
the way it seems to me is that you are already in a JS context when you open the `${...}`, could be the case that this is changing context again from JS back to CSS. I think the object notation seems more straightforward

**Comment by chrisdwheatley** [comment]
Having re-looked at this I agree @adaschevici. Object notation makes more sense at this point.
