### ISSUE TITLE
Split default theme out into separate package

### ISSUE THREAD

**Issue by chrisdwheatley** [nearform/saluki#79]
**Is your feature request related to a problem? Please describe.**

If you're not interested in using the default Saluki theme then there's currently no way of opting out.

The downsides of the current solution of embedding the default theme within Saluki are;

* An increased bundle size which includes JavaScript not necessarily needed
* Any rules that aren't overridden stick around, meaning they could be used by someone when not necessarily wanted

**Describe the solution you'd like**

Split the default Saluki theme out into it's own module and then allow users to decide whether they want to manually pass it in or not.

For example;

```jsx
import { ThemeProvider } from "styled-components/macro";
import { theme } from "saluki";
import defaultTheme from "saluki-default-theme";

export const newTheme = {
  color: {
    red: "pink"
  }
};

export default () => (
  <ThemeProvider theme={theme(defaultTheme, newTheme)}>
    <App />
  </ThemeProvider>
);
```

The idea is that if you don't want to use Saluki's defaults you don't have to. And if you do then you can and can still override with a second argument.

Some benefits to this approach;

* If you've already got an existing theme you're happy with you can use it without polluting it with any Saluki defaults
* If you want to use your own custom theme without extending Saluki's default theme simply pass it in as the first argument without the need to override
* This solution decouples Saluki's default theme from it's helper methods, meaning custom themes could be written to work with Saluki, e.g. a Tailwind default theme or Tachyons default theme which port over their rules into the Saluki ecosystem.

Possible downsides;

* Saluki's `theme` function probably isn't the best name now, might need renaming to something like `createTheme`.

**Describe alternatives you've considered**

I'm not 100% sure on the API yet to allow both custom default themes as well as extensions and overrides. I'm happy for suggestions/thoughts on this.

**Comment by chrisdwheatley** [comment]
@simoneb, @adaschevici would be interested in getting your opinion on this idea.

**Comment by simoneb** [comment]
I like the idea, yes!

**Comment by chrisdwheatley** [comment]
Implemented in https://github.com/nearform/saluki/pull/81
